### ISSUE TITLE
Loading strings from .csv file

### ISSUE THREAD

**Issue by sowmith1729** [harp-lab/slog-lang1#49]
Dumping relations with string facts loaded from CSV causes a key error in the REPL, This is true for the Main Branch as well.

## How to recreate?
For this rule
```slog
[(foobar x y) <-- (foo x y) (bar y)]
```
with bar.csv and foo.csv respectively as follows in the facts folder
```bar.csv
"foo"
"bar"
```
```foo.csv
1	"foo"
2	"bar"
```
Run slog as follows
```
./runslog -R --facts /slog/slog/tests/testcase/stringtest/input/ /slog/slog/tests/testcase/stringtest/stringtest.slog /slog-examples/output_string/
```
and once in the REPL either `dump foo` or `dump bar`, REPL will exit with a key error.
<details>
  <summary>Error Message</summary>

      
          A Parallel Datalog Engine!
          Type `help` to see help information.
      
      
      σλoγ [LOCAL] » relations
      Relation name  Arity  # Tuples  Tag    Size (KiB)
      
      bar            1      2         256     0.02
      foo            2      2         257     0.03
      foobar         2      2         258     0.03
      
      Total tuples: 6
      Command cost       0.00 sec.
      σλoγ [LOCAL] » dump bar
      256 >>>>>>>> [256]
      Traceback (most recent call last):
        File "/slog/./runslog", line 401, in <module>
          run_local(slogfile, args.out_dir, args.facts, args.cores, args.verbose, args.root,
        File "/slog/./runslog", line 302, in run_local
          repl.loop()
        File "/slog/slog/repl/repl.py", line 344, in loop
          exec_command(self.client, text)
        File "/slog/slog/repl/repl.py", line 158, in exec_command
          client.dump_relation_by_name(args[0], ConsoleWriter())
        File "/slog/slog/common/client.py", line 479, in dump_relation_by_name
          for pp_str in tuple_parser.pretty_str_tuples(rels):
        File "/slog/slog/common/tuple.py", line 158, in pretty_str_tuples
          pp_str = self.tuple_to_str(val, self.max_depth)
        File "/slog/slog/common/tuple.py", line 124, in tuple_to_str
          res.append(self.intern_string_dict[col.sid])
      KeyError: 5150719049391

</details>

### Issue
The hashing of strings in the intern_dict stored by the REPL seems to be different than when the query res is being parsed and the string has to be queried from the interned strings. This is only the case for the strings loaded from the .csv file. I am not sure why/where are they being treated differently.

#48 is the draft PR for this issue.

**Comment by sowmith1729** [comment]
#48 Fixed this.
